backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

site_url: https://europeanen-jamstack.netlify.com/

logo_url: "{{site_url}}/images/logo_MEN.png"

local_backend: true

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - label: "Author"
        name: "author"
        widget: relation
        collection: "author"
        displayFields: ["name"]
        searchFields: ["name"]
        valueField: "name"
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Publicatiedatum", name: "date", widget: "datetime"}
      - {label: "Samenvatting", name: "description", widget: "text"}
      - {label: "Foto", name: "featuredimage", widget: image, required: false}
      - {label: "Featured Image beschrijving", name: "featuredimage_alt", widget: string}
      - label: "Bijlage"
        name: "attachment"
        widget: file
        required: false
      - {label: "Bijlage weergavenaam", name: "attachment_description", widget: string, required: false }
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", required: false}

  - name: "author"
    label: "Authors"
    label_singular: "Author"
    description: "List of authors available on the platform"
    folder: "src/authors"
    create: true
    delete: "false"
    identifier_field: "name"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "author"}
      - {label: "Naam", name: "name", widget: string}
      - {label: "Titel", name: "job_title", widget: string}
      - {label: "Profielfoto", name: "profile_picture", widget: image, allow_multiple: false}

  - name: "pages"
    label: "Pages"
    delete: true
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Over de Europeanen titel", name: about_title, widget: string}
          - {label: "Over de Europeanen content", name: about_content, widget: text}
          - {label: "Over de Europeanen meer knop titel", name: about_button_title, widget: string}
          - {label: "Nieuws titel", name: news_title, widget: string}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}